.eslintignore, .eslintrc.js, package-lock.json, package.json, src/server/server.js
Added a basic copy of eslint config (copied from fe-blogs)
Fixed couple of "errors" from eslint report.
=> Add eslint confict

package-lock.json, package.json, src/server/App.jsx, src/server/server.js
=> Added emotion css rendering

.eslintrc.js, package-lock.json, package.json, src/server/server.js, src/server/template.js, src/server/template.test.js
-`Jest` setup 
- `template` tests
- pre-push hook executing tests
=> unit tests added

package.json, src/server/index.js, src/server/server.js
=> Added linting to pre push hook

src/app/components/page.js, src/app/styles/color.js, src/app/styles/font-face.js, src/app/styles/font-family.js, src/app/styles/typography.js
Added variables for:
- colors
- font-family
- typography
=> Add style variables for future use in emotion based components.

package-lock.json, package.json, src/app/components/__snapshots__/article-description.test.js.snap, src/app/components/__snapshots__/article-main-image.test.js.snap, src/app/components/__snapshots__/article-publication-details.test.js.snap, src/app/components/__snapshots__/share-bar.test.js.snap, src/app/components/article-description.js, src/app/components/article-main-image.js, src/app/components/article-publication-details.js, src/app/components/article.js, src/app/components/share-bar.js, src/app/components/share-bar.test.js, src/app/components/styled-share-bar.js, src/app/styles/icon-sizes.js, src/server/get-graphql-data.js, src/server/template.js
Added share bar to an article.
Updated some styles to match main site.
=> AMP-20 Share bar under the main image on article page

src/server/server.js
In production environment we want to send redirect to main site if article is not available for free.
=> Send redirect to main site for unfree articles

src/server/config.js, src/server/config/base-config.js, src/server/config/economist.js, src/server/get-graphql-data.js, src/server/handlers/amp-page-render.js, src/server/handlers/amp-page-render.test.js, src/server/handlers/healthcheck.js, src/server/handlers/healthcheck.test.js, src/server/index.js, src/server/render-html.js, src/server/server.js, src/server/utils/environment-detection.js
- `healtcheck` endpoint test added 
- refactored `config` files
- added `utils/environment-detection.js`
- small fixes 'n' tidying up
=> AMP-9 healtcheck follow up

src/app/components/article/__snapshots__/article-publication-details.test.js.snap, src/app/components/footer/__snapshots__/footer-social-menu.test.js.snap, src/app/components/footer/__snapshots__/footer.test.js.snap, src/app/components/footer/footer-social-menu.js, src/app/components/navigation-menu/__snapshots__/navigation-menu.test.js.snap, src/app/components/navigation-menu/__snapshots__/styled-accordion-list.test.js.snap, src/app/components/navigation/__snapshots__/navigation.test.js.snap, src/app/components/navigation/navigation.js, src/app/components/styled-icon-button/__snapshots__/styled-icon-button.test.js.snap, src/app/components/styled-icon-button/styled-icon-button.js, src/app/components/styled-share-bar/__snapshots__/styled-share-bar.test.js.snap, src/app/components/styled-share-bar/styled-share-bar.js, src/server/template.js
Added aria-labels and lang to html tag.
Improves Accessibility score to 75% according to Lighthouse.
=> AMP-49 Improvements to Accessibility

package.json, src/server/handlers/healthcheck.js, src/server/handlers/healthcheck.test.js
- tests commend change
- minor test refactoring
=> Test commands restructuring

src/app/components/article/article-publication-details.js
=> AMP-62 fix section color link

package-lock.json, src/server/handlers/amp-page-render.js, src/server/handlers/amp-page-render.test.js, src/server/handlers/healthcheck.js, src/server/handlers/healthcheck.test.js, src/server/handlers/root-redirect.js, src/server/handlers/root-redirect.test.js, src/server/index.js, src/server/server.js
small PR with server handlers tests refactoring.
We stop using server mocking as it was a bit strange causing race conditions and random timeouts
now we just mock h object and test actual functionality of paths handlers 
no ticket for this no need to QA (or maybe for regression )
=> server handleres tests refactoring

src/app/components/story-collection/story-collection-hero-item.js, src/app/components/story-collection/story-collection-item.js
Editors pick missing section link fix 
(removes whole link if there is no data from server
)
=> missing links data fix

src/app/components/article/article-text-builder.js
=> Fixing console prop type errors

package-lock.json, package.json
https://jira.economist.com/browse/AMP-53
=> AMP-53 - Updating component-404 to latest version

package-lock.json, src/app/components/article/__snapshots__/article-main-image.test.js.snap, src/app/components/article/__snapshots__/article-text-builder.test.js.snap, src/app/components/footer/__snapshots__/footer.test.js.snap, src/app/components/footer/footer.js, src/app/components/image/__snapshots__/image.test.js.snap, src/app/components/story-collection/__snapshots__/story-collection-hero-item.test.js.snap, src/app/components/story-collection/__snapshots__/story-collection-item.test.js.snap, src/app/components/story-collection/__snapshots__/story-collection.test.js.snap, src/app/styles/page-sizes.js
footer change,
I dont think we need QA for this one ? or do we ?
=> footer size update

package-lock.json, src/app/components/page/page.js, src/app/components/user-consent/user-consent.js, src/server/handlers/amp-page-render.js, src/server/handlers/check-consent.js, src/server/server.js, src/server/template.js
Added cookie consent dialog.
To show the dialog, we send `check-consent.json` request. In this request we check existence of Evidon cookie.
=> AMP-75 Cookie Consent for AMP

src/app/components/user-consent/user-consent.js, src/server/handlers/check-consent.js, src/server/handlers/cors-extension.js, src/server/utils/get-url.js
Fixed issue with relative path.
Added support for CORS requests.
=> AMP-80 Cookie banner is not displayed in Production

src/server/handlers/cors-extension.js
Reverts EconomistDigitalSolutions/amp#71
=> Revert "add more debugging info"

src/server/handlers/cors-extension.js
Reverts EconomistDigitalSolutions/amp#70
=> Revert "Add debug info for cors error"
